export { default as Navbar } from "../components/navbar/Navbar"
export { default as Header } from "../components/header/Header"
export { default as Location } from "../components/location/Location"
export { default as Activity } from "../components/activity/Activity"
export { default as Popular } from "../components/popular/Popular"
export { default as Shared } from "../components/shared-photos/Shared"
export { default as Testimonials } from "../components/testimonials/Testimonials"
export { default as News } from "../components/news-letter/News"
export {default as Footer} from "../components/footer/Footer"